name: ci
on: [push]

env:
  BUILD_DIR: './build'
  NODE_VERSION: '14'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            /tmp/.yarn_cache
          key: v5-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Yarn
        run: yarn --pure-lockfile --cache-folder /tmp/.yarn_cache
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ${{ env.BUILD_DIR }}
          if-no-files-found: error
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            /tmp/.yarn_cache
          key: v5-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Yarn
        run: yarn --pure-lockfile --cache-folder /tmp/.yarn_cache
      - name: Jest
        run: yarn test

  deployWebsite:
    needs:
      - build
      - test
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: fregante/setup-git-user@v1
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            /tmp/.yarn_cache
          key: v5-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Yarn
        run: yarn --pure-lockfile --cache-folder /tmp/.yarn_cache
      - uses: actions/download-artifact@v2
        with:
          name: build
          path: ${{ env.BUILD_DIR }}
      - name: Deploy website
        run: yarn deploy
